CREATE DATABASE LLocadora_DDL;
USE LLocadora_DDL;

CREATE TABLE Marcas(
	IdMarca		INT PRIMARY KEY IDENTITY,
	Nome		VARCHAR(200)
);

CREATE TABLE Modelos(
	IdModelo	INT PRIMARY KEY IDENTITY,
	Nome		VARCHAR(200),
	IdMarca		INT FOREIGN KEY REFERENCES Marcas (IdMarca)
);

CREATE TABLE Empresa(
	IdEmpresa	INT PRIMARY KEY IDENTITY,
	Nome		VARCHAR(200)
);

CREATE TABLE Veiculo(
	IdVeiculo	INT PRIMARY KEY IDENTITY,
	IdEmpresa	INT FOREIGN KEY REFERENCES Empresa (IdEmpresa),
	IdModelo	INT FOREIGN KEY REFERENCES Modelos (IdModelo),
	Placa		VARCHAR(200)
);

CREATE TABLE Cliente(
	IdCliente	INT PRIMARY KEY IDENTITY,
	Nome		VARCHAR(200),
	CPF			CHAR(11)
);

CREATE TABLE Aluguel(
	IdAluguel	INT PRIMARY KEY IDENTITY,
	IdCliente	INT FOREIGN KEY REFERENCES Cliente (IdCliente),
	IdVeiculo	INT FOREIGN KEY REFERENCES Veiculo (IdVeiculo),
	DataInicio	DATE,
	DataFim		DATE
);




